# Generated by Django 3.2.16 on 2022-11-15 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='phone',
            new_name='no_hp_pengguna',
        ),
        migrations.AlterModelTable(
            name='customuser',
            table='pengguna',
        ),
    ]
