# Generated by Django 3.2.16 on 2022-11-15 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20221116_0018'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'pengguna'},
        ),
    ]
