# Generated by Django 3.2.16 on 2022-11-15 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_customuser_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detailfakturpembelian',
            options={'verbose_name_plural': 'detail faktur pembelian'},
        ),
        migrations.AlterModelOptions(
            name='detailfakturpenjualan',
            options={'verbose_name_plural': 'detail faktur penjualan'},
        ),
        migrations.AlterModelOptions(
            name='detailproduk',
            options={'verbose_name_plural': 'detail produk'},
        ),
        migrations.AlterModelOptions(
            name='distributor',
            options={'verbose_name_plural': 'distributor'},
        ),
        migrations.AlterModelOptions(
            name='fakturpembelian',
            options={'verbose_name_plural': 'faktur pembelian'},
        ),
        migrations.AlterModelOptions(
            name='fakturpenjualan',
            options={'verbose_name_plural': 'faktur penjualan'},
        ),
        migrations.AlterModelOptions(
            name='jenisproduk',
            options={'verbose_name_plural': 'jenis produk'},
        ),
        migrations.AlterModelOptions(
            name='konsumen',
            options={'verbose_name_plural': 'konsumen'},
        ),
        migrations.AlterModelOptions(
            name='petugas',
            options={'verbose_name_plural': 'petugas'},
        ),
        migrations.AlterModelOptions(
            name='produk',
            options={'verbose_name_plural': 'produk'},
        ),
    ]
