# Generated by Django 3.2.16 on 2022-11-15 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20221116_0047'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='id',
            new_name='id_pengguna',
        ),
    ]
