# Generated by Django 3.2.16 on 2022-11-15 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_rename_id_customuser_id_pengguna'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detailfakturpembelian',
            old_name='id',
            new_name='id_detail_faktur_pembelian',
        ),
        migrations.RenameField(
            model_name='detailfakturpembelian',
            old_name='produk',
            new_name='id_produk',
        ),
        migrations.RenameField(
            model_name='detailfakturpembelian',
            old_name='faktur_pembelian',
            new_name='no_faktur_pembelian',
        ),
        migrations.RenameField(
            model_name='detailfakturpenjualan',
            old_name='id',
            new_name='id_detail_faktur_penjualan',
        ),
        migrations.RenameField(
            model_name='detailfakturpenjualan',
            old_name='produk',
            new_name='id_produk',
        ),
        migrations.RenameField(
            model_name='detailfakturpenjualan',
            old_name='faktur_penjualan',
            new_name='no_faktur_penjualan',
        ),
        migrations.RenameField(
            model_name='detailproduk',
            old_name='id',
            new_name='id_detail_produk',
        ),
        migrations.RenameField(
            model_name='detailproduk',
            old_name='produk',
            new_name='id_produk',
        ),
        migrations.RenameField(
            model_name='detailproduk',
            old_name='faktur_pembelian',
            new_name='no_faktur_pembelian',
        ),
        migrations.RenameField(
            model_name='distributor',
            old_name='id',
            new_name='id_distributor',
        ),
        migrations.RenameField(
            model_name='fakturpembelian',
            old_name='pengguna',
            new_name='id_pengguna',
        ),
        migrations.RenameField(
            model_name='fakturpembelian',
            old_name='id',
            new_name='no_faktur_pembelian',
        ),
        migrations.RenameField(
            model_name='fakturpenjualan',
            old_name='konsumen',
            new_name='id_konsumen',
        ),
        migrations.RenameField(
            model_name='fakturpenjualan',
            old_name='id',
            new_name='no_faktur_penjualan',
        ),
        migrations.RenameField(
            model_name='jenisproduk',
            old_name='id',
            new_name='id_jenis_produk',
        ),
        migrations.RenameField(
            model_name='konsumen',
            old_name='id',
            new_name='id_konsumen',
        ),
        migrations.RenameField(
            model_name='petugas',
            old_name='distributor',
            new_name='id_distributor',
        ),
        migrations.RenameField(
            model_name='petugas',
            old_name='id',
            new_name='id_petugas',
        ),
        migrations.RenameField(
            model_name='produk',
            old_name='jenis_produk',
            new_name='id_jenis_produk',
        ),
        migrations.RenameField(
            model_name='produk',
            old_name='id',
            new_name='id_produk',
        ),
        migrations.AddField(
            model_name='fakturpembelian',
            name='id_petugas',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.petugas'),
        ),
    ]
