# Generated by Django 3.2.16 on 2022-11-15 18:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20221116_0106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fakturpembelian',
            name='id_pengguna',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='id_pengguna'),
        ),
        migrations.AlterField(
            model_name='fakturpembelian',
            name='id_petugas',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.petugas', verbose_name='id_petugas'),
        ),
    ]
