# Generated by Django 3.2.16 on 2022-11-15 18:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20221116_0115'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detailfakturpembelian',
            old_name='no_faktur_pembelian',
            new_name='faktur_pembelian',
        ),
        migrations.RenameField(
            model_name='detailfakturpembelian',
            old_name='id_detail_faktur_pembelian',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='detailfakturpembelian',
            old_name='id_produk',
            new_name='produk',
        ),
        migrations.RenameField(
            model_name='detailfakturpenjualan',
            old_name='no_faktur_penjualan',
            new_name='faktur_penjualan',
        ),
        migrations.RenameField(
            model_name='detailfakturpenjualan',
            old_name='id_detail_faktur_penjualan',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='detailfakturpenjualan',
            old_name='id_produk',
            new_name='produk',
        ),
        migrations.RenameField(
            model_name='detailproduk',
            old_name='no_faktur_pembelian',
            new_name='faktur_pembelian',
        ),
        migrations.RenameField(
            model_name='detailproduk',
            old_name='id_detail_produk',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='detailproduk',
            old_name='id_produk',
            new_name='produk',
        ),
        migrations.RenameField(
            model_name='distributor',
            old_name='id_distributor',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='fakturpenjualan',
            old_name='no_faktur_penjualan',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='fakturpenjualan',
            old_name='id_konsumen',
            new_name='konsumen',
        ),
        migrations.RenameField(
            model_name='jenisproduk',
            old_name='id_jenis_produk',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='konsumen',
            old_name='id_konsumen',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='petugas',
            old_name='id_distributor',
            new_name='distributor',
        ),
        migrations.RenameField(
            model_name='petugas',
            old_name='id_petugas',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='produk',
            old_name='id_produk',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='produk',
            old_name='id_jenis_produk',
            new_name='jenis_produk',
        ),
        migrations.RemoveField(
            model_name='fakturpembelian',
            name='id_pengguna',
        ),
        migrations.RemoveField(
            model_name='fakturpembelian',
            name='id_petugas',
        ),
        migrations.AddField(
            model_name='fakturpembelian',
            name='pengguna',
            field=models.ForeignKey(db_column='id_pengguna', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fakturpembelian',
            name='petugas',
            field=models.ForeignKey(db_column='id_petugas', null=True, on_delete=django.db.models.deletion.CASCADE, to='home.petugas'),
        ),
    ]
