# Generated by Django 3.2.16 on 2022-11-15 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20221116_0125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detailfakturpembelian',
            old_name='id',
            new_name='id_detail_faktur_pembelian',
        ),
        migrations.RenameField(
            model_name='detailfakturpenjualan',
            old_name='id',
            new_name='id_detail_faktur_penjualan',
        ),
        migrations.RenameField(
            model_name='detailproduk',
            old_name='id',
            new_name='id_detail_produk',
        ),
        migrations.RenameField(
            model_name='distributor',
            old_name='id',
            new_name='id_distributor',
        ),
        migrations.RenameField(
            model_name='fakturpenjualan',
            old_name='id',
            new_name='id_faktur_penjualan',
        ),
        migrations.RenameField(
            model_name='jenisproduk',
            old_name='id',
            new_name='id_jenis_produk',
        ),
        migrations.RenameField(
            model_name='konsumen',
            old_name='id',
            new_name='id_konsumen',
        ),
        migrations.RenameField(
            model_name='petugas',
            old_name='id',
            new_name='id_petugas',
        ),
        migrations.RenameField(
            model_name='produk',
            old_name='id',
            new_name='id_produk',
        ),
        migrations.AlterField(
            model_name='detailfakturpembelian',
            name='faktur_pembelian',
            field=models.ForeignKey(db_column='no_faktur_pembelian', on_delete=django.db.models.deletion.CASCADE, to='home.fakturpembelian'),
        ),
        migrations.AlterField(
            model_name='detailfakturpembelian',
            name='produk',
            field=models.ForeignKey(db_column='id_produk', on_delete=django.db.models.deletion.CASCADE, to='home.produk'),
        ),
        migrations.AlterField(
            model_name='detailfakturpenjualan',
            name='faktur_penjualan',
            field=models.ForeignKey(db_column='no_faktur_penjualan', on_delete=django.db.models.deletion.CASCADE, to='home.fakturpenjualan'),
        ),
        migrations.AlterField(
            model_name='detailfakturpenjualan',
            name='produk',
            field=models.ForeignKey(db_column='id_produk', on_delete=django.db.models.deletion.CASCADE, to='home.produk'),
        ),
        migrations.AlterField(
            model_name='detailproduk',
            name='faktur_pembelian',
            field=models.ForeignKey(db_column='no_faktur_pembelian', on_delete=django.db.models.deletion.CASCADE, to='home.fakturpembelian'),
        ),
        migrations.AlterField(
            model_name='detailproduk',
            name='produk',
            field=models.ForeignKey(db_column='id_produk', on_delete=django.db.models.deletion.CASCADE, to='home.produk'),
        ),
        migrations.AlterField(
            model_name='fakturpenjualan',
            name='konsumen',
            field=models.ForeignKey(db_column='id_konsumen', on_delete=django.db.models.deletion.CASCADE, to='home.konsumen'),
        ),
        migrations.AlterField(
            model_name='petugas',
            name='distributor',
            field=models.ForeignKey(db_column='id_distributor', on_delete=django.db.models.deletion.CASCADE, to='home.distributor'),
        ),
        migrations.AlterField(
            model_name='produk',
            name='jenis_produk',
            field=models.ForeignKey(db_column='id_jenis_produk', on_delete=django.db.models.deletion.CASCADE, to='home.jenisproduk'),
        ),
    ]
