# Generated by Django 3.2.16 on 2022-11-15 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20221116_0134'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='nama_pengguna',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
