# Generated by Django 3.2.16 on 2022-11-15 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_customuser_nama_pengguna'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fakturpenjualan',
            old_name='id_faktur_penjualan',
            new_name='no_faktur_penjualan',
        ),
    ]
