# Generated by Django 3.2.16 on 2022-12-08 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_rename_id_faktur_penjualan_fakturpenjualan_no_faktur_penjualan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='nama_pengguna',
            new_name='nama_lengkap',
        ),
    ]
