# Generated by Django 3.2.16 on 2022-12-08 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_rename_nama_pengguna_customuser_nama_lengkap'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detailfakturpenjualan',
            name='produk',
        ),
        migrations.AddField(
            model_name='detailfakturpenjualan',
            name='produk',
            field=models.ManyToManyField(db_column='id_produk', to='home.Produk'),
        ),
    ]
