# Generated by Django 3.2.16 on 2022-12-08 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20221209_0204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detailfakturpenjualan',
            name='produk',
        ),
        migrations.AddField(
            model_name='detailfakturpenjualan',
            name='produk',
            field=models.ForeignKey(db_column='id_produk', null=True, on_delete=django.db.models.deletion.CASCADE, to='home.produk'),
        ),
    ]
