# Generated by Django 3.2.16 on 2022-12-08 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20221209_0246'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailfakturpenjualan',
            name='jumlah_produk',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
