# Generated by Django 3.2.16 on 2022-12-21 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_detailfakturpenjualan_jumlah_produk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailproduk',
            name='faktur_pembelian',
            field=models.ForeignKey(db_column='no_faktur_pembelian', null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.fakturpembelian'),
        ),
    ]
