# Generated by Django 3.2.16 on 2023-01-04 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_alter_detailproduk_faktur_pembelian'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detailfakturpenjualan',
            name='produk',
        ),
        migrations.AddField(
            model_name='detailfakturpenjualan',
            name='produk',
            field=models.ManyToManyField(db_column='id_produk', to='home.Produk'),
        ),
    ]
