# Generated by Django 3.2.16 on 2023-01-04 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_auto_20230105_0142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailfakturpenjualan',
            name='jumlah_produk',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
