# Generated by Django 3.2.16 on 2023-01-04 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_alter_detailfakturpenjualan_jumlah_produk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detailfakturpenjualan',
            name='jumlah_produk',
        ),
    ]
