# Generated by Django 3.2.16 on 2023-01-04 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_remove_detailfakturpenjualan_jumlah_produk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailfakturpenjualan',
            name='kuantitas',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
