# Generated by Django 3.2.16 on 2023-01-07 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_alter_detailfakturpenjualan_kuantitas'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DetailFakturPenjualan',
        ),
    ]
