# Generated by Django 3.2.16 on 2023-01-07 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_auto_20230107_1640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detailfakturpenjualan',
            name='kuantitas',
        ),
    ]
