# Generated by Django 3.2.16 on 2023-02-20 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_remove_customuser_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Margin',
            fields=[
                ('id_margin', models.AutoField(primary_key=True, serialize=False)),
                ('margin', models.FloatField()),
            ],
        ),
    ]
